[project]
name = "rberga06-phylab"
version = "0.1.0"
description = "A small Python library for random daily use in the Physics laboratory"
authors = [
    {name = "RBerga06", email = "78449715+RBerga06@users.noreply.github.com"},
]
dependencies = []
requires-python = ">=3.12"
readme = "README.md"
license = {text = "AGPL-3.0-only"}

[tool.pdm.build]
package-dir = "src"
includes = ["src/rberga06/"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
